name = "MyTreeNode"
uuid = "a14f1419-5400-4e44-9f4a-b29412dda653"
authors = ["Donghoon Lee <mdhe1248@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
